language: node_js
node_js:
  - "10"

cache: npm
  
services:
  - docker

script:
  - npm install -g @angular/cli@6.0.8
  - npm install
  - ng build
  
deploy:
  provider: script
  script: bash deploy.sh
  on: 
    tags: true
