language: node_js
node_js:
  - "10"

cache: npm
  
services:
  - docker

script:
  - npm install -g @angular/cli@6.0.8
  - npm install
  - ng build
  
deploy:
  provider: script
  script: 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - docker build -t mrblnetwork/panel .
    - docker push mrblnetwork/panel
    - "docker tag mrblnetwork/panel mrblnetwork/panel:$TRAVIS_TAG"
    - "docker push mrblnetwork/panel:$TRAVIS_TAG"
  on: 
    tags: true
